---
version: 0.1
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
retryOnFailure: true
runson: linux
cypress: true
maxRetries: 1
concurrency: 10
autosplit: true
pre:
  - npm install
  - npm install cypress --save-dev
  - npm i lambdatest-cypress-cli   
cacheKey: '{{ checksum "package.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  mode: static
  type: raw
  command: ls cypress/e2e/2-advanced-examples
testRunnerCommand: npx cypress run  --spec ./cypress/e2e/2-advanced-examples/actions.cy.js --browser=chrome-126.0 --headed --config video=true
cypressOps:
  Build: "Hyperexecute Cypress Sample Build"
  Tags: ["Hyperexecute","Cypress", "Windows", "Autosplit"]
  BuildTags: ["Hyperexecute-Cypress"]
  accessibility: true
  accessibilityWcagVersion: "wcag21a"
  accessibilityBestPractice: false  
  accessibilityNeedsReview: true

post:
  - cat yaml/linux/.hyperexecute_autosplit.yaml

jobLabel: [cypress-v10, linux, autosplit]